linters:
  enable-all: true
  disable:
    - exportloopref
    - depguard
    - tparallel
    - paralleltest
    - mnd
linters-settings:
  funlen:
    lines: 200
    statements: 150
  gci:
    sections:
      - standard
      - default
      - localmodule
  godox:
    keywords: ["FIXME"]
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)
  exhaustruct:
    include:
      - '.+/system\.[a-zA-Z0-9]+$'
      - '.+/repo\.[a-zA-Z0-9]+$'
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
  varnamelen:
    ignore-names:
      - xs
    ignore-decls:
      - ok bool
      - i int
      - j int
      - id gid.ID
      - x float64
      - y float64
  wsl:
    allow-cuddle-declarations: true
