name: "Build & Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
          
    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.63.4
